# Generated by Django 5.2.17 on 2026-09-20 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Nomi"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="Manzil qismi"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        help_text="Nakleykadagi rang, HEX ko'rinishida. Masalan: #E87B93",
                        max_length=16,
                        verbose_name="Rangi",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nakleykadagi tartib bo'yicha",
                        verbose_name="Tartibi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Hadith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="QR kod shu qiymatni ochadi. Masalan: ilm-01",
                        max_length=64,
                        unique=True,
                        verbose_name="Manzil qismi",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Loyiha tomonidan yoziladi — manbadan emas. Ro'yxatda va sahifa tepasida ko'rinadi.",
                        max_length=160,
                        verbose_name="Sarlavha",
                    ),
                ),
                (
                    "paper_text",
                    models.TextField(
                        help_text="Qog'ozchaga sig'ishi uchun 280 belgidan oshmasligi kerak.",
                        verbose_name="Qog'ozcha matni",
                    ),
                ),
                (
                    "paper_source_line",
                    models.CharField(
                        help_text="Masalan: Muslim, 2699 — Abu Hurayradan",
                        max_length=160,
                        verbose_name="Qog'ozcha manba qatori",
                    ),
                ),
                ("arabic_text", models.TextField(verbose_name="Arabcha matn")),
                ("uzbek_full", models.TextField(verbose_name="O'zbekcha tarjima")),
                ("narrator", models.CharField(max_length=160, verbose_name="Roviy")),
                (
                    "collection",
                    models.CharField(
                        help_text="Masalan: Sahih Muslim",
                        max_length=120,
                        verbose_name="To'plam",
                    ),
                ),
                (
                    "collection_no",
                    models.CharField(max_length=32, verbose_name="To'plamdagi raqami"),
                ),
                (
                    "grade",
                    models.CharField(
                        help_text="Masalan: Sahih — Imom Muslim rivoyati",
                        max_length=120,
                        verbose_name="Daraja",
                    ),
                ),
                (
                    "ref_book",
                    models.CharField(
                        help_text="Masalan: Riyozus solihiyn, 1400-hadis",
                        max_length=160,
                        verbose_name="Kitob",
                    ),
                ),
                (
                    "ref_url",
                    models.URLField(blank=True, verbose_name="Manbadagi sahifa"),
                ),
                (
                    "sharh",
                    models.TextField(
                        blank=True,
                        help_text="Manbadan so'zma-so'z. Bo'sh qoldirilsa, sahifada «sharh berilmagan» holati ko'rsatiladi.",
                        verbose_name="Sharh",
                    ),
                ),
                (
                    "sharh_ref",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Sharh manbasi"
                    ),
                ),
                (
                    "sharh_url",
                    models.URLField(blank=True, verbose_name="Sharh sahifasi"),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False,
                        help_text="Diniy ekspertizadan o'tgach belgilanadi. Belgilanmagan hadislar saytda ko'rinmaydi.",
                        verbose_name="Chop etilgan",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartibi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hadislar",
                        to="hadis.category",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hadis",
                "verbose_name_plural": "Hadislar",
                "ordering": ("category__order", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="FullText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uzbek_full",
                    models.TextField(verbose_name="Asl hadisning to'liq tarjimasi"),
                ),
                ("ref_book", models.CharField(max_length=160, verbose_name="Kitob")),
                (
                    "ref_url",
                    models.URLField(blank=True, verbose_name="Manbadagi sahifa"),
                ),
                (
                    "hadith",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="full_text",
                        to="hadis.hadith",
                        verbose_name="Hadis",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'liq matn",
                "verbose_name_plural": "To'liq matnlar",
            },
        ),
    ]
