# Generated by Django 5.2.17 on 2026-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith',
            name='qr_code',
            field=models.ImageField(blank=True, help_text="Qog'ozchadagi QR kod rasmi (https://nurulhadis.uz/h/<slug> manziliga).", upload_to='qr/', verbose_name='QR kod'),
        ),
    ]
