# Generated by Django 5.2.17 on 2026-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadis', '0002_hadith_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('kind', models.CharField(choices=[('view', 'Kirish'), ('click', 'Bosish')], max_length=10, verbose_name='Turi')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='Sahifa')),
                ('visitor', models.CharField(db_index=True, max_length=40, verbose_name='Tashrifchi')),
                ('device', models.CharField(blank=True, max_length=10, verbose_name='Qurilma')),
                ('from_ad', models.BooleanField(default=False, verbose_name='Reklamadan')),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=80)),
                ('utm_content', models.CharField(blank=True, max_length=80)),
                ('referrer', models.CharField(blank=True, max_length=200, verbose_name='Qayerdan')),
            ],
            options={
                'verbose_name': 'Statistika yozuvi',
                'verbose_name_plural': 'Statistika',
                'ordering': ['-created'],
            },
        ),
    ]
